// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxO-FpTDWn2-yYPaxtcHP47w51cRZlM4g',
    appId: '1:980995471354:web:813c6b705633b9e2af9643',
    messagingSenderId: '980995471354',
    projectId: 'shrine-matching-f1a77',
    authDomain: 'shrine-matching-f1a77.firebaseapp.com',
    storageBucket: 'shrine-matching-f1a77.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf9Ox7JXR6qjIf8-PUeexySRuq5-KZZ30',
    appId: '1:980995471354:android:74e8066754c96378af9643',
    messagingSenderId: '980995471354',
    projectId: 'shrine-matching-f1a77',
    storageBucket: 'shrine-matching-f1a77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyitjETgyiZ3o1LC1i-xRrh2U8THQpbNI',
    appId: '1:980995471354:ios:48d0ec2cba0a391daf9643',
    messagingSenderId: '980995471354',
    projectId: 'shrine-matching-f1a77',
    storageBucket: 'shrine-matching-f1a77.firebasestorage.app',
    iosBundleId: 'com.example.shrineMatching',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyitjETgyiZ3o1LC1i-xRrh2U8THQpbNI',
    appId: '1:980995471354:ios:48d0ec2cba0a391daf9643',
    messagingSenderId: '980995471354',
    projectId: 'shrine-matching-f1a77',
    storageBucket: 'shrine-matching-f1a77.firebasestorage.app',
    iosBundleId: 'com.example.shrineMatching',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxO-FpTDWn2-yYPaxtcHP47w51cRZlM4g',
    appId: '1:980995471354:web:fa67d3c3ac4998dbaf9643',
    messagingSenderId: '980995471354',
    projectId: 'shrine-matching-f1a77',
    authDomain: 'shrine-matching-f1a77.firebaseapp.com',
    storageBucket: 'shrine-matching-f1a77.firebasestorage.app',
  );
}
